portfolio/__init__.py
from flask import Flask, url_for, redirect, render_template, session, request
from portfolio.routes.projects_blueprint import projects
from portfolio.routes.contact_blueprint import contact
from portfolio.routes.about_blueprint import about


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'temporary_secret_key_for_session_themes'

    @app.route("/")
    def home_redirect():
        return redirect(url_for("projects.Projects"))

    @app.errorhandler(404)
    def not_found(error):
        return render_template("error/404.html"), 404
    
    @app.route("/theme")
    def swap_theme():
        if "theme" not in session or session["theme"] == "dark":
            session["theme"] = "light"
        else:
            session["theme"] = "dark"
        return redirect(request.referrer)

    app.register_blueprint(projects, url_prefix="/projects")
    app.register_blueprint(contact, url_prefix="/contact")
    app.register_blueprint(about, url_prefix="/about")

    return app

portfolio/routes/about_blueprint.py
from flask import Blueprint, render_template

about = Blueprint("about", __name__)

@about.route("/")
def About():
    return render_template("about.html", title="About me", page="about")

portfolio/routes/contact_blueprint.py
from flask import Blueprint, render_template


contact = Blueprint("contact", __name__)

@contact.route("/")
def Contact():
    return render_template("contact.html", title="My contact", page="contact")

portfolio/routes/projects_blueprint.py
from flask import Blueprint, render_template, abort, session

projects = Blueprint("projects", __name__)

projects_list = [
    {
        "technologies": "Python | Flask | HTML | CSS | MongoDB",
        "description": "Simple note taking app. Created it under the guidance of Jose Salvatierra during 'Web Developer Bootcamp with Flask and Python in 2024' Udemy course.",
        "image": "noteup.png",
        "slug": "noteup"
    },
    {
        "technologies": "Python | Flask | HTML | CSS | MongoDB",
        "description": "App for rating and tracking your watched movies. Created it under the guidance of Jose Salvatierra during 'Web Developer Bootcamp with Flask and Python in 2024' Udemy course.",
        "image": "movies.png",
        "slug": "movies"
    },
    {
        "technologies": "HTML | CSS | Python | Flask",
        "description": "My very own portfolio website. This is the website you are currently looking at with all the information about me and my projects",
        "image": "portfolio.png",
        "slug": "portfolio"
    }
]

slugs = [project["slug"] for project in projects_list]

@projects.route("/")
def Projects():
    if "theme" in session:
        print(session["theme"])
    return render_template("projects.html", title="My projects", projects=projects_list)

@projects.route("/<string:slug>")
def Projects_noteup(slug):
    if slug in slugs:
        return render_template(slug + ".html", title=f"My projects - {slug}", page="")
    else:
        abort(404)

portfolio/templates/about.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/article_style.css') }}">
{% endblock %}

{% block main %}
    <main class="main">

        <!-- <div class="main__banner">
            <img class="main__banner-image" src="{{ url_for('static', filename='code.png') }}" alt="Photo of code">
            <h1 class="main__banner-glow"></h1>
        </div> -->

        <section class="main__about-section-main">    
                <h1 class="main__section-header" >Introduction <i class="fa-solid fa-panorama main__section-header"></i></h1>
                <p class="main__section-content">
                    Hey! I’m Piotr, a junior developer who’s been passionate about coding since I was young. These days, I’m focused on building web applications and growing into a great back-end developer.
                    Most of my work so far has been with Python specifically Flask and Django, but I’ve also been picking up JavaScript and Rust along the way.
                    I love experimenting with projects that challenge me and push me to learn something new. My goal is to become a well-rounded full-stack developer, but I’m especially drawn to back-end development because I enjoy working with databases and server-side logic.
                    When I’m not coding, I like to unwind by playing video games or spending time with my cat.
                </p>    
        </section>

        <section class="main__about-section">
                <div class="main__section-text">
                <h1 class="main__section-header">My projects <i class="fa-solid fa-list-check main__section-header"></i></h1>
                <p class="main__section-content">  
                    So far, I’ve built apps like NoteUp, a simple note-taking tool, and Movies, an app for rating your favorite films. I’m continuously expanding my portfolio piece by piece.
                    Even though I enjoy back-end development the most, I’m also working on improving my front-end skills so I can create full-stack projects from start to finish.
                    My portfolio is still growing, I’m proud of the progress even projects that are in works were able to teach me a lot.
                </p>
                </div>  
                <div class="main__side-block">
                <h3 class="main__side-block-header">Main skills <i class="fa-solid fa-dumbbell main__side-block-header"></i></h3>
                <ul class="main__side-block-content">
                    <li><i class="fa-brands fa-python"></i> Python</li>
                    <li><i class="fa-brands fa-html5"></i> HTML</li>
                    <li><i class="fa-brands fa-css3-alt"></i> CSS</li>
                    <li><i class="fa-solid fa-database"></i> NoSQL/SQL</li>
                </ul>
            </div>
        </section>

        <section class="main__about-section">
            <h1 class="main__section-header">Here is my kitty <i class="fa-solid fa-cat main__section-header"></i></h1>
            <img class="main__image" src="{{url_for('static', filename='cat.JPG')}}" alt="My own kitty">
        </section>


        <section class="main__about-section">
            <h1 class="main__section-header" >My achievements <i class="fa-solid fa-trophy main__section-header"></i></h1>
            <p class="main__section-content">
                One of my proudest achievements must be my ability to intuitively learn new programming languages and frameworks on my own.
                My knowledge may not be too vast yet, but I’m a quick learner and always eager to take on new challenges.
                I finished my high school diploma with a focus on IT, which laid a solid foundation for my coding journey.
                Additionally, I’ve earned a certificate from Udemy for completing a comprehensive web development courses.
                I am constatly pushing myself to improve and expand my skill set by taking on new projects and learning opportunities.
            </p>
        </section>

        <section class="main__about-section">
            <h1 class="main__section-header" >Next projects <i class="fa-solid fa-bullseye main__section-header"></i></h1>
            <p class="main__section-content">
                Looking ahead, I have several exciting projects in the pipeline. I’m currently working on a inventory management system designed to help school I graduated from.
                So far project is mostly finished and I am really happy with how much I learned during its development. It required me to learn many new things like AWS S3 integration and user authentication using Microsoft Azure. 
                More on that in this project section you can take a look at it <a class="main__section-link" target="_blank" href="{{url_for('projects.Projects')}}">here</a>.
                Another project I plan to work on is a secure way to store and manage secrets and environment variables for developers.
                This tool will help developers keep their sensitive information safe while still being easily accessible during development and deployment.
                I’m excited about these upcoming projects and the opportunity to continue growing as a developer. Stay tuned for updates as I make progress on these initiatives!
                Keep looking for more info in the <a class="main__section-link" target="_blank" href="{{url_for('projects.Projects')}}">project</a> section.
            </p>
        </section>

        <section class="main__about-section">    
                <h1 class="main__section-header" >Full skills list <i class="fa-solid fa-medal main__section-header"></i></h1>
                <ul class="main__section-content-list">
                    <li><span class="main__section-content-list-important">Python</span> (Flask, Django, Pymongo, SQLAlchemy)</li>
                    <li><span class="main__section-content-list-important">JavaScript</span></li>
                    <li><span class="main__section-content-list-important">Rust</span></li>
                    <li><span class="main__section-content-list-important">HTML5 & CSS3</span></li>
                    <li><span class="main__section-content-list-important">Databases:</span> MySQL, SQLite, MongoDB</li>
                    <li><span class="main__section-content-list-important">Version Control:</span> Git & GitHub</li>
                    <li>Basic knowledge of Docker and containerization</li>
                    <li>Familiarity with RESTful API design and development</li>
                    <li>Problem-solving skills honed through coding challenges on Codewars <span class="main__section-content-list-important">(4 kyu)</span></li>
                </ul>
        </section>


        <section class="main__about-section">
                <h1 class="main__section-header">Certificates <i class="fa-solid fa-certificate main__section-header"></i></h2>
                <ul class="main__section-content">
                    <li class="main__certificate">
                        <a class="main__link" target="_blank" href="https://www.udemy.com/certificate/UC-52457cb8-ff16-43f7-9f2c-5556d5443b72/">
                            <h3 class="main__certificate-header">Web Developer Bootcamp with Flask and Python in 2024</h3>
                            <img class="main__certificate-image" src="{{ url_for('static', filename='Udemy_certificate_1.jpg') }}">
                        </a>
                    </li>
                </ol>
        </section>
    </main>

{% endblock %}

portfolio/templates/base.html
<!doctype html>
<html lang="en" class="{{ 'light-theme' if 'theme' in session and session['theme'] == 'light' }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,600' rel='stylesheet'>
    <link rel="icon" href="{{ url_for('static', filename='my_photo.jpg') }}">
    <script src="https://kit.fontawesome.com/d8d81b7e15.js" crossorigin="anonymous"></script>
    <title>Krzastek | {{ title }}</title>
    {% block style %}
    {% endblock %}
</head>
<body>
    <a class="main__toggle-theme" href="{{ url_for('swap_theme') }}">
        {% if "theme" in session and session["theme"] == "light" %}
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-moon" viewBox="0 0 16 16">
            <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278M4.858 1.311A7.27 7.27 0 0 0 1.025 7.71c0 4.02 3.279 7.276 7.319 7.276a7.32 7.32 0 0 0 5.205-2.162q-.506.063-1.029.063c-4.61 0-8.343-3.714-8.343-8.29 0-1.167.242-2.278.681-3.286"/>
            </svg>
        {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-sun" viewBox="0 0 16 16">
            <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6m0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0m0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13m8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5M3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8m10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0m-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0m9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707M4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708"/>
            </svg>
        {% endif %}
    </a>
    <div class="main_body">
        <header class="header">
            <img class="header__avatar" src="{{ url_for('static', filename='my_photo.jpg') }}">
            <h1>Piotr Krząstek</h1>
            <p class="header__subtitle">Junior web developer</p>
        </header>

        <nav class="nav">
            <ul class="nav__list">
                <li class="nav__list-element {{ 'nav__list-current' if request.path == url_for('projects.Projects')}}"><a class="nav__list-element_link" href="{{ url_for('projects.Projects') }}">Projects</a> </li>
                <li class="nav__list-element {{ 'nav__list-current' if request.path == url_for('about.About')}}"><a class="nav__list-element_link" href="{{ url_for('about.About') }}">About me</a> </li>
                <li class="nav__list-element {{ 'nav__list-current' if request.path == url_for('contact.Contact')}}"><a class="nav__list-element_link" href="{{ url_for('contact.Contact') }}">Contact</a> </li>
            </ul>
        </nav>
        {% block main %}
        {% endblock %}
    </div>

    <footer class="footer">
        <div class="footer__left">
            <p>Copyright © 2025 Piotr Krząstek. All rights reserved.</p>
        </div>
        <div class="footer__right">
            <div class="footer__icons">
                <a target="_blank" class="footer__logo" href="https://www.linkedin.com/in/krzastek">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                    </svg>
                </a>
                <a target="_blank" class="footer__logo" href="https://github.com/PiotrKrzastek">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                    </svg>
                </a>
            </div>
        </div>
    </footer>

</body>
</html>

portfolio/templates/contact.html
{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/contact_style.css') }}">
{% endblock %}

{% block main %}
    <main class="main">

        <p class="main__name"><i class="fa-solid fa-envelope main__name"></i> Email</p>
        <a class="main__link" href="mailto:piotrkrzastek05@gmail.com">piotrkrzastek05@gmail.com</a>

        <p class="main__name"><i class="fa-brands fa-github main__name"></i> Github</p>
        <a class="main__link" target="_blank" href="https://github.com/PiotrKrzastek">@PiotrKrzastek</a>

        <p class="main__name"><i class="fa-brands fa-linkedin main__name"></i>Linkedin</p>
        <a class="main__link" target="_blank" href="https://www.linkedin.com/in/krzastek/">@Piotr krząstek</a>

        <p class="main__name"><i class="fa-solid fa-gamepad main__name"></i> Codewars</p>
        <a class="main__link" target="_blank" href="https://www.codewars.com/users/Polkissss">@Polkissss</a>
    </main>
{% endblock %}

portfolio/templates/macros/project_macros.jinja2
{% macro project_card(technologies, description, image, link) %}
    <article class="main__card">
        <a class=main__card-link href="{{link}}">
            <img class="main__card-image {% if frame %} image_frame {% endif %} " src="{{image}}" alt="project photo">
            <h4 class="main__card-header">{{ technologies }}</h4>
            <p class="main__card-description"> {{ description }}</p>
        </a>
    </article>
{% endmacro%}

portfolio/templates/movies.html
{% from "macros/project_macros.jinja2" import project_card %}

{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/article_style.css') }}">
{% endblock %}

{% block main %}
    <main class="main">
        <div class="main__banner">
            <img class="main__banner-image" src="{{ url_for('static', filename='movies.png') }}">
            <h1 class="main__banner-glow"></h1>
        </div>

        <section class="main__about-section-main">
            <h1 class="main__section-header" >Movies</h1>
            <p class="main__section-content">
                Movies is a really simple web application where users can track their last watched movies and it's ratings as well as share this information with friends.
                This was one of my key projects from the Udemy course <a class="main__section-link" target="_blank" href="https://www.udemy.com/course/web-developer-bootcamp-flask-python/">Web Developer Bootcamp with Flask and Python in 2024</a>.
                It can be considered as my final test before completing the course and earning my certificate.
            </p>
        </section>

        <section class="main__about-section">
            <div class="main__section-text">
                <h1 class="main__section-header">Features <i class="fa-solid fa-star main__section-header"></i></h1>
                <p class="main__section-content">
                    Movies allows users to create a free account and add any movie they want to keep their ratings and last watch dates in one place.
                    You can completely customize your movie page by adding description, short video, cast, genres and series. 
                    That way you can know exactly when was the last time you watched a particular movie and change it's rating whenever you feel like it.
                    You could as well send your friends a link to your movie so they can see your rating and the way you customized it's page.
                </p>
            </div>
            <div class="main__side-block">
                <h3 class="main__side-block-header">Tech stack <i class="fa-solid fa-microchip main__side-block-header"></i> </h3>
                <ul class="main__side-block-content">
                    <li>
                        <i class="fa-brands fa-python"></i><p>Python/Flask</p>
                    </li>
                    <li>
                        <i class="fa-brands fa-html5"></i><p>HTML</p>
                    </li>
                    <li>
                        <i class="fa-brands fa-css3-alt"></i><p>CSS</p>
                    </li>
                    <li>
                        <i class="fa-solid fa-database"></i><p>MongoDB</p>
                    </li>
                </ul>
            </div>
        </section>

        <section class="main__about-section">
                <h1 class="main__section-header" >Screenshots <i class="fa-solid fa-image main__section-header"></i></h2>
                <p class="main__section-content">
                    The style on this website is the same as the one in the course since I knew im not gonna develop more on this and used it as a practice and challenge for my CSS skills.
                    Regardless it contains two themes dark and light you can use one or the other depending on your preferences. 
                    The site is really simple but I tried to make it as pretty as I can since CSS is not something I enjoy writing.
                </p>
                <img class="main__image" src="{{url_for('static', filename='movies.png')}}" alt="movies screenshot - main page">
                <img class="main__image" src="{{url_for('static', filename='movies_screenshot1.png')}}" alt="movies screenshot - movie page example">
                <img class="main__image" src="{{url_for('static', filename='movies_screenshot2.png')}}" alt="movies screenshot - register page">
                <img class="main__image" src="{{url_for('static', filename='movies_screenshot3.png')}}" alt="movies screenshot - white theme add movie page">
        </section>

        <section class="main__about-section">
            <h1 class="main__section-header" >Quickstart <i class="fa-solid fa-play main__section-header"></i></h1>
            <p class="main__section-content">
                To host this app, simply clone the repo at the bottom of this site, then you just install all the requirements in pip.
                If you did previous steps create .env file in your project directory with DBURI inside where you pass your Mongo database URI. Once done you just simply use "flask run" in your command line to run the application.
            </p>
        </section>

        <section class="main__about-section">
            <h1 class="main__section-header" >Security <i class="fa-solid fa-shield main__section-header"></i></h1>
            <p class="main__section-content">
                Movies takes user password security seriously. All sensitive data in the database is hashed using the <a target="_blank" class="main__section-link" href="https://passlib.readthedocs.io/en/stable/">passlib</a> python library, ensuring passwords are stored securely.
                <br><br>
                It's important to note that if you share a direct link to a specific movie page with another registered user, that user will be able to modify the content of that page. This is due to the way the application was originally designed during the course. While I could implement access controls to restrict editing, I've chosen to focus my development efforts on other projects with higher priority.
                <br><br>
                If you have concerns about this behavior, you are welcome to implement your own access controls and host the application privately, or submit a pull request with your improvements.
            </p>
        </section>

        <section class="main__about-section">
            <h1 class="main__section-header">Roadmap <i class="fa-solid fa-road main__section-header"></i></h1>
            <div class="roadmap">
                <ul class="roadmap__list">
                    <li class="roadmap__item roadmap__item-completed">
                        <span class="roadmap__bullet"><i class="fa-solid fa-check"></i></span>
                        <a class="roadmap__text">Initial Release with user authentication and every planned feature.</a>
                    </li>
                    <li class="roadmap__item roadmap__item--current">
                        <span class="roadmap__bullet"></span>
                        <a class="roadmap__text">Support for this project has ended. As sad as it sounds for now I feel like I should focus on my other apps like ekonomik inventory or securenv to better enhance my skills as a developer.</a>
                    </li>
                </ul>
            </div>
        </section>

        <section class="main__about-section">
            <h1 class="main__section-header" >Troubleshooting <i class="fa-solid fa-wrench "></i></h1>
            <p class="main__section-content">
               If something doesn't work make sure you installed everything from requirements.txt and your .env has exactly one variable DBURI.
               Once you made sure you have set up everything perfectly and app still doesn't work or works but not as intended feel free to <a target="_blank" class="main__section-link" href="{{url_for('contact.Contact')}}">contact me</a> and I will do my best to help you and possibly create a following FAQ section.
            </p>
        </section>

        <section class="main__about-section-links">
                    <p class="main__name"><i class="fa-brands fa-github main__name"></i>Repository:</p>
                    <a class="main__link" style="font-size: 24px;" target="_blank" href="https://github.com/PiotrKrzastek/movie_watchlist">github.com/PiotrKrzastek/movie_watchlist</a>
                    
                    <p class="main__name"><i class="fa-solid fa-earth-americas main__name"></i>Live website</p>
                    <a class="main__link" style="font-size: 24px;" target="_blank" href="https://movie-watchlist-sgo6.onrender.com/home">movie-watchlist-sgo6.onrender.com/home</a>
        </section>

    </main>
{% endblock %}

portfolio/templates/projects.html
{% from "macros/project_macros.jinja2" import project_card %}

{% extends "base.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/projects_style.css') }}">
{% endblock %}

{% block main %}
    <main class="main">
        {% for project in projects %}
            {{ project_card(project.technologies, project.description, url_for('static', filename=project.image), "/projects/" + project.slug)}}
        {% endfor %}
    </main>
{% endblock %}